# Generated by Django 4.2.7 on 2025-10-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_date_monthlybalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
