# Generated by Django 4.2.7 on 2025-11-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybalance',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
