# Generated by Django 4.2.7 on 2025-11-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_full_name_user_phone_user_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('IN', 'India'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('AU', 'Australia'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('JP', 'Japan'), ('CN', 'China'), ('BR', 'Brazil'), ('MX', 'Mexico'), ('SG', 'Singapore'), ('AE', 'UAE'), ('SA', 'Saudi Arabia'), ('ZA', 'South Africa'), ('NG', 'Nigeria'), ('KE', 'Kenya')], default='US', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='auth_user_email_ece7f7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='auth_user_usernam_f2740e_idx'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
